config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    get 'about', to: 'pages#about'
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  
  resources:categories, except: [:destroy]
  resources:articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence:true, length: {minimum: 3, maximum: 50}
    validates :user_id, presence: true
    
    
    
    
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: {maximum: 25, minimum: 3}
    validates_uniqueness_of :name
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 105}, format: { with: VALID_EMAIL_REGEX }
    
    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
        !!current_user
    end
    
    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform this message."
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only:[:edit,:update,:destroy]
    
    
    def index
       @articles = Article.paginate(page: params[:page], per_page: 5)
       
    end
   
    def new
        @article = Article.new
    end
  
    def create
        
        #render plain: params[:article].inspect
        @article = Article.new(article_params)
        @article.save
        @article.user = current_user
        #Checking to make sure validations go through
        if @article.save 
            flash[:success] = "The article was successfully submitted."
            redirect_to article_path(@article)
        else

            render 'new'
        end
        
    end 
    
    def show 
        @article = Article.find(params[:id])
    end
    
    def edit
        @article = Article.find(params[:id])
        
    end
    
    def update
         @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:success] = "The article was successfully updated."
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end 
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash[:danger] = "Article was successfully deleted."
        redirect_to articles_path
    end
    
    private 
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end
    def require_same_user
        @article = Article.find(params[:id])
        if current_user != @article.user and !current_user.admin?
           flash["danger"] = "You do not have the required permissions to do that."
           redirect_to root_path
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    
    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end
    def new
        @category = Category.new
    end
    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end
    def edit
        @category = Category.find(params[:id])
    end
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Category name was successfully edited."
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end
    def create
        @category = Category.new(category_params)
        if @category.save 
            flash[:success] = "Category was created successfully!"
            redirect_to categories_path
        else
            render 'new'
        end
    end
    
    private 
    def category_params
        params.require(:category).permit(:name)
    end
    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger] = "Only admins can perform that action."
            redirect_to categories_path
        end
        
        
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    
    def about
    
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        
    end
    
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in."
            redirect_to user_path(user)
            
        else
            flash.now[:danger] = "Email or password was incorrect, or no account found."
            render 'new'
            
            
        end
        
    end
    
    
    def destroy
        session[:user_id]  = nil
        flash[:success] = "You have been logged out."
        redirect_to root_path
        
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    
    def index
       @users = User.paginate(page: params[:page], per_page: 5)
    end
   
    def new
        @user = User.new
    end
    
    def create 
       @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
           flash[:success] = "Welcome to the alpha blog #{@user.username}"
           redirect_to user_path(@user)
        else
          render 'new'
        end
    end
    
    def edit
        
    end
    
    def update
        if @user.update(user_params)
            flash[:success] = "Your Account was Successfully Updated."
            redirect_to articles_path
        else
            render 'edit'
            
        end
        
    end
    
    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end
    
    def destroy
       @user = User.find(params[:id])
       @user.destroy
       flash[:danger] = "The user and all of the user's articles have been deleted."
       redirect_to users_path
    end
    
    
    private
    def user_params
       params.require(:user).permit(:username, :email, :password) 
    end
    
    def set_user
       @user = User.find(params[:id]) 
    end
    
    def require_same_user
        if current_user != @user and !current_user.admin?
           flash[:danger] = "You do not have permissions to do that."
           redirect_to root_path
        end
    end
    
    def require_admin
       if logged_in?  and !current_user.admin?
          flash[:danger] = "Only admins can perform that action."
          redirect_to root_path
       end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <div class="card card-lg" id= "articleCards">
                <div class="article-title">
                    <%= link_to article.title, article_path(article), class: "articleTitleCustom" %>
                </div>
                <%if article.categories.any? %>
                    <p>Categories: <%= render article.categories%></p>
                <%end%>
                <div class="article-body">
                    <%= truncate(article.description, length: 100) %>
                    <div class = "article-meta-details">
                        <small>Created by: <%= article.user.username if article.user %></small>,
                        <small><%= time_ago_in_words(article.created_at) %> ago,
                        last updated: <%=time_ago_in_words(article.updated_at) %> ago.</small> 
                    </div>
                    
                                         
                </div>

                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                    <div class="article-actions">
                        <%= link_to "Edit this Article", edit_article_path(article), class: "btn btn-sm btn-primary" %>
                        <%= link_to "Delete Article", article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class: "btn btn-sm btn-danger" %>  
                    </div>
                <%end%>
            </div>
        </div>
    </div>

    <%end%>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class= "row">
    <div class= 'col-sm-12 offset-sm-1'>
       
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do  |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :title %>
               
            </div>
             
    
            <div class="col-sm-10">
                
                  <%= f.text_field :title, class:"form-control", placeholder: "Title of article", autofocus: true %> 
            </div>
        </div>

  
          <div class="form-group">
            <div class="control-label col-sm-2">      
                <%= f.label :description %>
            </div>
            <div class="col-sm-10">
               <%= f.text_area :description, rows: 10, class:"form-control", placeholder: "Body of article" %>
            </div>
                
             <div class="form-group"  id="dropdown">
                    <div class="col-sm-offset-2 col-sm-10">
                         <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, {:item_wrapper_class => 'checkbox_container'} do |cb| %>
                             <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                         <%end%>
                    </div>
            </div>            
            
            <div class="form-group" id="submitbutton">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit  class: "btn btn-primary btn-large" %>
                </div>
                
            </div>
                

            
            <div class="col-sm-4 offset-sm-3" align="center">
             [  <%= link_to "Cancel request and return to articles", articles_path %> ]
            </div>
            
                
            
        
        <%end%>
        
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center"> Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align = "center">Listing all articles</h1>
<div class = "col-md-6 offset-md-5" align = "center">
    <div align = "center">
         <%= will_paginate @clients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>
<%= render 'article', obj: @articles %>
<div class = "col-md-6 offset-md-5" align = "center">
    <div align = "center">
         <%= will_paginate @clients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>

app/views/articles/new.html.erb
<h1 align="Center">
    Create a new article
</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align = "center">
    <%= @article.title %>
    
</h2>

<div class="card col-md-8 offset-md-2">
    <% if @article.user %>
        <ul class = "listing">
            <div class = "row">
                <div class = "col-md-6 offset-md-3" align = "center" id = "nameplate">
                    <li>Created By:</li>
                    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                    <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
                    <li><small><%=pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
                </div>
            </div>
    </ul>
    <%end%>
    <%if @article.categories.any?%>
        <p>Categories: <%= render @article.categories%></p>
    <%end%>
    <h4 align="center"><strong>Description:</strong></h4>
    <hr>
    <%= simple_format(@article.description)%>
    <div class="article-actions">
        <%if logged_in? && (current_user == @article.user || current_user.admin?)%>
            <%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-sm btn-primary" %>
            <%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class: "btn btn-sm btn-danger" %>  
        <%end%>
        <%= link_to "View all articles", articles_path, class: "btn btn-sm btn-success" %>  
    </div>

</div>
   

   

app/views/categories/_category.html.erb
<span class = "badge badge-secondary">
    <%= link_to category.name, category_path(category)%> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do  |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :name %>
           
        </div>
         

        <div class="col-sm-10">
            
              <%= f.text_field :name, class:"form-control", placeholder: "Enter category name", autofocus: true %> 
        </div>
    </div>
    <div class="form-group" id="submitbutton">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-primary btn-large" %>
        </div>

    </div>
                
            
        
    <%end%>

app/views/categories/edit.html.erb
<h1 align = "center">Edit Category Name</h1>

<%= render 'form'%>

app/views/categories/index.html.erb
<h1 align = "Center">Showing All Categories</h1>
<div class = "col-md-6 offset-md-5" align = "center">
    <div align = "center">
         <%= will_paginate @clients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>
<% @categories.each do |category| %>
    <ul class = "listing">
        <div class = "row">
            <div class = "card col-md-4 offset-md-4" align = "center">
                <div class = "article-title">
                    <%= link_to "#{category.name}", category_path(category) %>
                    <li><small><%= pluralize(category.articles.count, "article")%></small></li>
                </div>
            </div>    
        </div>

    </ul>
<%end%>
<div class = "col-md-6 offset-md-5" align = "center">
    <div align = "center">
         <%= will_paginate @clients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>

app/views/categories/new.html.erb
<h1 align = "center">Create New Category</h1>

<%= render 'form' %>
        

app/views/categories/show.html.erb
<h1 align = "center"><%= "Category " + @category.name %></h1>
<div class = "col-md-6 offset-md-5" align = "center">
    <div align = "center">
        <% if logged_in? and current_user.admin? %>
            <div class = "row">
                    <span class = "badge badge-secondary"><%= link_to "Edit Category Name", edit_category_path(@category)%></span>
            </div>
        <%end%>
         <%= will_paginate @category_articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div class = "col-md-6 offset-md-5" align = "center">
    <div align = "center">
         <%= will_paginate @category_articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue" id="footerz">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 Copyright nonexistent
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-12 col-sm-offset-1">
    <% flash.each do |name,msg| %>
      <div class=' alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        
      </div>

    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "Submit Article",new_article_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View Profile", user_path(current_user), class: "nav-link" %>
            <%= link_to "Edit Your Profile", edit_user_path(current_user), class: "nav-link" %>

          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "All Categories", categories_path, class: "nav-link" %>
            <% Category.all.each do |category| %>
              <%= link_to "#{category.name}", category_path(category), class: "nav-link" %>
            <%end%>
          </div>
        </li>
        <% if current_user.admin?%>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Admin
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Add New Category", new_category_path, class: "nav-link" %>
                <%= link_to "Edit Your Profile", edit_user_path(current_user), class: "nav-link" %>
    
              </div>
          </li>
        <%end%>
        <li class="nav-item"><%= link_to "Log Out", logout_path, method: :delete, class: "nav-link" %></li>
      <%else%>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item"><%= link_to "Log In", login_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Sign Up", signup_path, class: "nav-link" %></li>
      <%end%>
      
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Helloworld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    
    <%= render 'layouts/messages' %>
    <div class= "container">
       <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
   
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is Chase yooo</h1>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-4">What's up my homedogs?</h1>
  <p class="lead">Welcome to the best blog ever written.  Brought to you by world-renowned author, Chase Florom</p>
  <hr class="my-4">
  <p>This website is not liable if it blows your gosh darn mind.</p>
  <p class="lead">

    <%= link_to "Blow my Mind", signup_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>

<div class="row">
          <div class="col-md-4">
            <h2>I don't do anything</h2>
            <p>But I did go above and beyond the tutorial!  Yes I sure did.  And I challenge Paul to do something equally as cool on his page.  Is he up for the challenge?  We shall see! </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div>
          <div class="col-md-4">
            <h2>Samesies</h2>
            <p>But I did go above and beyond the tutorial!  Yes I sure did.  And I challenge Paul to do something equally as cool on his page.  Is he up for the challenge?  We shall see! </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div>
          <div class="col-md-4">
            <h2>I do something!  Just kidding I don't :(</h2>
            <p>But I did go above and beyond the tutorial!  Yes I sure did.  And I challenge Paul to do something equally as cool on his page.  Is he up for the challenge?  We shall see! </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
          </div>


</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-sm-10">
            <div class="alert alert-danger">
                <div class="alert-heading">
                    <h2 class="alert-title" id="errorHeader">
                        <%=pluralize(obj.errors.count, "error") %>
                        prohibited this from being saved:
                    </h2>
                    <div class="alert-body">
                        <ul>
                          <% obj.errors.full_messages.each do |msg| %>
                                <li><%=msg%></li>
                            <%end%>  
                        </ul>
                            
                    </div>
                </div>
                
            </div>
        </div>
    </div>
<%end%>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class= "row">
    <div class= 'col-sm-12'>
       
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do  |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :username %>
               
            </div>
             
    
            <div class="col-sm-10">
                
                  <%= f.text_field :username, class:"form-control", placeholder: "Enter Username", autofocus: true %> 
            </div>
        </div>

  
        <div class="form-group">
            <div class="control-label col-sm-2">      
                <%= f.label :email %>
            </div>
            <div class="col-sm-10">
               <%= f.email_field :email, rows: 10, class:"form-control", placeholder: "Enter Email" %>
            </div>
        </div>
        
        <div class="form-group">
            <div class="control-label col-sm-2">      
                <%= f.label :password %>
            </div>
            <div class="col-sm-10">
               <%= f.password_field :password, class:"form-control", placeholder: "Enter Password" %>
            </div>
        </div>
                
            
        <div class="form-group" id="submitbutton">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit(@user.new_record? ? "Sign up" : "Update Account",  class: "btn btn-primary btn-large") %>
            </div>

        </div>
                    
                
            
        <%end%>
        
    </div>
</div>

app/views/users/edit.html.erb
<h1 align= "center"> Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align = "center">All Alpha Bloggers</h1>

<div class = "col-md-6 offset-md-5" align = "center">
    <div align = "center">
         <%= will_paginate @clients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>


<% @users.each do |user| %>
    <ul class = "listing">
        <div class = "row">
            <div class = "card col-md-6 offset-md-3" align = "center">
                <li><%= link_to gravatar_for(user), user_path(user) %></li>
                <li class="article-title"><%= link_to user.username, user_path(user) %></li>
                <li><small><%=pluralize(user.articles.count, "article") if user.articles %></small></li>
                <% if logged_in? and current_user.admin?%>
                    <li><%= link_to "Delete This User", user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user?"} %></li>
                <%end%>
            </div>
        </div>
    </ul>
<%end%>

<div class = "col-md-6 offset-md-5" align = "center">
    <div align = "center">
         <%= will_paginate @clients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align = "center">Welcome to <%=@user.username%>'s page</h1>
<div class = "row">
    <div class = "col-md-12 col-md-offset-8" align = "center">
        <%= gravatar_for @user, size: 150%>
    </div>
</div>
<h4 align = "center"><%= @user.username%>'s articles</h4>

<div class = "col-md-12 offset-md-5" align = "center">
    <div align = "center">
         <%= will_paginate @user_articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>

<%= render 'articles/article', obj: @user_articles %>